### ISSUE TITLE
[Suggestion] 更多弹幕源支持

### ISSUE THREAD

**Issue by ghost** [zaxtyson/AnimeSearcherOld#3]
目前项目只有 Bilibili 作为弹幕源，来源有限，可否考虑添加更多弹幕源支持。
接口来源可参考项目 [KikoPlay/Play/Danmu/Provider at master · Protostars/KikoPlay](https://github.com/Protostars/KikoPlay/tree/master/Play/Danmu/Provider)
其中个人感觉其中 dandan (弹弹play) 的弹幕源最为全面和丰富。

**Comment by zaxtyson** [comment]
弹弹play 挺不错，之前就打算使用它，但是好像有一些弹幕匹配不到~
